<?php

namespace Database\Seeders;

use App\Models\AppearanceSetting;
use App\Models\Article;
use App\Models\ArticleCategory;
use App\Models\Category;
use App\Models\HomepageSection;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Review;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed Users (Super Admin, Customer)
        $admin = User::updateOrCreate(
            ['email' => 'admin@pamulangfish.com'],
            [
                'name' => 'Pamulang Fish Administrator',
                'password' => Hash::make('password'),
                'role' => 'super_admin',
                'phone' => '081234567890',
                'address' => 'Jl. Surya Kencana No. 88, Pamulang Barat, Tangerang Selatan',
            ]
        );

        $customer = User::updateOrCreate(
            ['email' => 'customer@pamulangfish.com'],
            [
                'name' => 'Budi Santoso',
                'password' => Hash::make('password'),
                'role' => 'customer',
                'phone' => '089876543210',
                'address' => 'Jl. Pajajaran No. 12, Pamulang, Tangerang Selatan',
            ]
        );

        // 2. Seed Default Appearance Settings (Aquatic Modern theme)
        AppearanceSetting::updateOrCreate(
            ['id' => 1],
            [
                'theme_mode' => 'light',
                'primary_color' => '#0284c7',       // Ocean Sky Blue
                'secondary_color' => '#059669',     // Aquatic Emerald
                'accent_color' => '#06b6d4',        // Vibrant Cyan
                'background_color' => '#f8fafc',
                'surface_color' => '#ffffff',
                'text_color' => '#0f172a',
                'muted_text_color' => '#64748b',
                'border_color' => '#e2e8f0',
                'font_family' => 'Plus Jakarta Sans',
                'body_font_size' => '15px',
                'heading_font_size' => '30px',
                'button_font_size' => '14px',
                'heading_font_weight' => '700',
                'body_font_weight' => '400',
                'border_radius' => '12px',
                'button_style' => 'solid',
                'navbar_style' => 'default',
                'site_title' => 'PAMULANGFISH',
                'site_tagline' => 'Khusus Ikan Cupang',
                'whatsapp_number' => '6281234567890',
                'whatsapp_button_text' => 'Tanya Spesimen',
                'announcement_active' => true,
                'announcement_text' => '🔥 Garansi Hidup 100% D.O.A (Death On Arrival) • Pengiriman Cepat Packing Oksigen 24 Jam • Khusus Spesimen Cupang Asli',
                'announcement_link' => '/catalog',
                'hero_badge' => '100% Spesialis Koleksi Ikan Cupang Hias & Kontes',
                'hero_title' => 'Toko Spesialis Khusus Ikan Cupang Hias',
                'hero_subtitle' => 'Pusat lelang & jual beli 100% khusus jenis ikan cupang pilihan: Halfmoon, Plakat, Crowntail (Serit), Giant, Double Tail, hingga Wild Betta. Murni spesialis Betta Fish berkualitas kontes dengan garansi hidup sampai tujuan.',
                'hero_btn_primary_text' => 'Belanja Sekarang',
                'hero_btn_primary_link' => '/catalog',
                'hero_btn_secondary_text' => 'Panduan Perawatan',
                'hero_btn_secondary_link' => '/articles',
                'trust_badge_1_val' => '100%',
                'trust_badge_1_lbl' => 'Garansi Hidup',
                'trust_badge_2_val' => 'Grade A+',
                'trust_badge_2_lbl' => 'Genetik Pilihan',
                'trust_badge_3_val' => '24 Jam',
                'trust_badge_3_lbl' => 'Packing Oksigen',
                'footer_about' => 'Platform e-commerce 100% spesialis ikan cupang hias (Betta Fish) terlengkap di Pamulang dengan kualitas genetik kontes dan garansi hidup selamat sampai tujuan (D.O.A 100%).',
                'footer_copyright' => '© 2026 Pamulang Fish Store. 100% Khusus Ikan Cupang Hias.',
                'guarantee_box_title' => 'Live Fish Guarantee (D.O.A)',
                'guarantee_box_text' => 'Garansi 100% penggantian ikan jika mati saat perjalanan via ekspedisi kilat (JNE YES / TIKI ONS) dengan video unboxing utuh tanpa jeda.',
                'logo_url' => null,
                'favicon_url' => null,
                'is_published' => true,
            ]
        );

        // 3. Seed Homepage Sections
        $sections = [
            [
                'section_key' => 'hero',
                'title' => 'Spesialis Ikan Cupang Hias (Betta Fish) Terbaik',
                'subtitle' => 'Koleksi 100% khusus berbagai varietas ikan cupang hias berkualitas kontes: Halfmoon, Plakat, Crowntail, Giant, dan Wild Betta dengan garansi hidup 100%.',
                'content' => json_encode(['cta_text' => 'Katalog Cupang', 'cta_link' => '#produk', 'secondary_cta' => 'Panduan Perawatan', 'secondary_link' => '#panduan']),
                'image' => '/images/hero-betta.jpg',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section_key' => 'categories',
                'title' => 'Jenis & Varietas Ikan Cupang',
                'subtitle' => 'Jelajahi seluruh klasifikasi dan variasi jenis ikan cupang hias unggulan kami.',
                'content' => null,
                'image' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section_key' => 'best_sellers',
                'title' => 'Ikan Cupang Terpopuler',
                'subtitle' => 'Koleksi cupang pilihan yang paling banyak diminati oleh pecinta betta fish.',
                'content' => null,
                'image' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section_key' => 'promo_banner',
                'title' => 'Garansi Pengiriman Ikan Cupang Hidup 100%',
                'subtitle' => 'Setiap pengiriman menggunakan packaging khusus tabung oksigen & sterofoam tebal dengan garansi D.O.A (Death on Arrival) sampai tujuan.',
                'content' => json_encode(['badge' => 'Special Care Betta']),
                'image' => null,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'section_key' => 'articles',
                'title' => 'Panduan & Edukasi Khusus Ikan Cupang',
                'subtitle' => 'Tips perawatan dari breeder berpengalaman untuk menjaga ikan cupang tetap sehat, aktif, dan berwarna cemerlang.',
                'content' => null,
                'image' => null,
                'sort_order' => 5,
                'is_active' => true,
            ],
        ];

        foreach ($sections as $sec) {
            HomepageSection::updateOrCreate(['section_key' => $sec['section_key']], $sec);
        }

        // 4. Seed Product Categories (100% Khusus Varietas Ikan Cupang)
        $categoriesData = [
            [
                'name' => 'Cupang Halfmoon (HM)',
                'slug' => 'halfmoon',
                'description' => 'Ikan cupang dengan bukaan sirip ekor setengah lingkaran 180 derajat sempurna, anggun, lebar, dan menawan.',
                'image' => '/images/categories/halfmoon.jpg',
                'icon' => 'fish',
                'sort_order' => 1,
            ],
            [
                'name' => 'Cupang Plakat (PK)',
                'slug' => 'plakat',
                'description' => 'Ikan cupang berekor pendek petarung yang lincah dengan sisik mutiara tebal dan corak paling populer.',
                'image' => '/images/categories/plakat.jpg',
                'icon' => 'shield',
                'sort_order' => 2,
            ],
            [
                'name' => 'Cupang Crowntail / Serit (CT)',
                'slug' => 'crowntail',
                'description' => 'Ikan cupang khas kebanggaan Indonesia dengan sirip dan ekor menyerupai mahkota berduri megah.',
                'image' => '/images/categories/crowntail.jpg',
                'icon' => 'crown',
                'sort_order' => 3,
            ],
            [
                'name' => 'Cupang Koi & Nemo Galaxy',
                'slug' => 'koi-nemo',
                'description' => 'Varian corak marble menyerupai ikan koi dengan taburan glitter sisik bintang galaksi berkilau.',
                'image' => '/images/categories/koi-nemo.jpg',
                'icon' => 'palette',
                'sort_order' => 4,
            ],
            [
                'name' => 'Cupang Giant (Raksasa)',
                'slug' => 'giant',
                'description' => 'Ikan cupang raksasa dengan ukuran panjang tubuh (BO) mencapai 6 hingga 7.5 cm yang berbobot tebal.',
                'image' => '/images/categories/giant.jpg',
                'icon' => 'maximize-2',
                'sort_order' => 5,
            ],
            [
                'name' => 'Cupang Double Tail / Cagak (DT)',
                'slug' => 'double-tail',
                'description' => 'Ikan cupang ekor ganda bercabang dua simetris dengan sirip dorsal punggung ekstra lebar.',
                'image' => '/images/categories/double-tail.jpg',
                'icon' => 'layers',
                'sort_order' => 6,
            ],
            [
                'name' => 'Cupang Dumbo Ear (Big Ear)',
                'slug' => 'dumbo-ear',
                'description' => 'Ikan cupang dengan sirip dayung dada melebar putih seperti telinga gajah yang berkibar eksotis.',
                'image' => '/images/categories/dumbo-ear.jpg',
                'icon' => 'feather',
                'sort_order' => 7,
            ],
            [
                'name' => 'Cupang Alien & Wild Hybrid',
                'slug' => 'alien-wild',
                'description' => 'Cupang hibrida alam liar (Wild Betta) dengan kilau jaring sisik metalik zamrud eksotis dan fisik prima.',
                'image' => '/images/categories/alien-wild.jpg',
                'icon' => 'zap',
                'sort_order' => 8,
            ],
        ];

        Category::whereNotIn('slug', array_column($categoriesData, 'slug'))->delete();

        $categories = [];
        foreach ($categoriesData as $c) {
            $categories[$c['slug']] = Category::updateOrCreate(['slug' => $c['slug']], $c);
        }

        // 5. Seed Comprehensive Specimen Products (100% Khusus Ikan Cupang Hias Indonesia)
        $productsData = [
            // --- HALFMOON ---
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon Blue Rim Grade A+',
                'slug' => 'ikan-cupang-halfmoon-blue-rim-grade-a',
                'sku' => 'HM-BR-001',
                'price' => 250000,
                'discount_price' => 199000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Blue Rim White Body',
                'size_cm' => 4.8,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Spesimen Halfmoon Blue Rim dengan bukaan ekor 180 derajat sempurna tanpa celah. List biru elektrik solid di sepanjang ujung sirip dengan tubuh putih salju bersih.',
                'care_guide' => 'Gunakan soliter kaca minimal 15x15x20 cm. Berikan ekstrak ketapang olahan dan pakan jentik/pelet spirulina 2 kali sehari.',
                'is_featured' => true,
                'image_path' => '/images/bettas/hm-bluerim.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon Super Red Solid',
                'slug' => 'ikan-cupang-halfmoon-super-red-solid',
                'sku' => 'HM-SR-002',
                'price' => 220000,
                'discount_price' => 180000,
                'stock' => 5,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Super Red Solid',
                'size_cm' => 4.6,
                'age_months' => 3.8,
                'care_level' => 'beginner',
                'description' => 'Halfmoon dengan warna merah darah solid merata dari moncong hingga ujung caudal. Mental ngedok garang dengan sirip dorsal mengembang penuh.',
                'care_guide' => 'Jaga kestabilan suhu air pada 26-28°C. Berikan kaca pancingan 5 menit per hari untuk melatih kebugaran sirip.',
                'is_featured' => true,
                'image_path' => '/images/bettas/hm-superred.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon Mustard Gas High Grade',
                'slug' => 'ikan-cupang-halfmoon-mustard-gas-high-grade',
                'sku' => 'HM-MG-003',
                'price' => 260000,
                'discount_price' => 215000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Mustard Gas (Blue & Yellow)',
                'size_cm' => 4.9,
                'age_months' => 4.2,
                'care_level' => 'intermediate',
                'description' => 'Perpaduan kontras warna royal blue gelap di badan dengan sirip ekor kuning kunyit cerah menyala. Bentuk ekor setengah lingkaran sangat proporsional.',
                'care_guide' => 'Gunakan air endapan minimal 24 jam dengan daun ketapang tua agar sirip tetap lentur dan tidak mudah kuncup.',
                'is_featured' => false,
                'image_path' => '/images/bettas/hm-mustardgas.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon White Platinum Metallic',
                'slug' => 'ikan-cupang-halfmoon-white-platinum-metallic',
                'sku' => 'HM-WP-004',
                'price' => 240000,
                'discount_price' => null,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'White Platinum Shimmer',
                'size_cm' => 4.7,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Tubuh dan seluruh sirip berwarna putih perak mutiara mengkilap memantulkan cahaya akuarium secara elegan. Bukaan caudal rapi dan tegap.',
                'care_guide' => 'Hindari pencahayaan terlalu terik langsung. Ganti air 30% dua kali seminggu dengan air bersuhu stabil.',
                'is_featured' => false,
                'image_path' => '/images/bettas/hm-whiteplatinum.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon Copper Black Mask',
                'slug' => 'ikan-cupang-halfmoon-copper-black-mask',
                'sku' => 'HM-CB-005',
                'price' => 275000,
                'discount_price' => 230000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Copper Black Metallic',
                'size_cm' => 4.8,
                'age_months' => 4.1,
                'care_level' => 'intermediate',
                'description' => 'Sirip dan badan memancarkan kilau tembaga metalik (copper) eksotis di atas warna dasar hitam pekat. Bukaan sirip mencapai 180° sempurna.',
                'care_guide' => 'Beri pakan hidup kaya protein (artemia/kutu air) untuk mempertahankan kemilau sisik tembaga.',
                'is_featured' => false,
                'image_path' => '/images/bettas/hm-copperblack.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon Lavender Butterfly',
                'slug' => 'ikan-cupang-halfmoon-lavender-butterfly',
                'sku' => 'HM-LB-006',
                'price' => 230000,
                'discount_price' => 195000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Lavender & White Margin',
                'size_cm' => 4.5,
                'age_months' => 3.9,
                'care_level' => 'beginner',
                'description' => 'Gradasi warna ungu lavender lembut dengan pola pita putih bersih (butterfly) di tepi seluruh sirip.',
                'care_guide' => 'Wadah soliter minimal 3 liter air dengan ekstrak ketapang ringan.',
                'is_featured' => false,
                'image_path' => '/images/bettas/hm-lavender.jpg',
            ],

            // --- PLAKAT ---
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Avatar Gordon High Grade',
                'slug' => 'ikan-cupang-plakat-avatar-gordon-high-grade',
                'sku' => 'PK-AV-007',
                'price' => 350000,
                'discount_price' => 285000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Black Blue Avatar Gordon',
                'size_cm' => 4.5,
                'age_months' => 3.5,
                'care_level' => 'intermediate',
                'description' => 'Plakat Avatar Gordon varietas paling diburu saat ini. Tubuh dasar hitam pekat legam dengan taburan bintik sisik mutiara biru elektrik menyala.',
                'care_guide' => 'Suhu ideal 26-28°C. Hindari air kaporit langsung, gunakan air endapan minimal 24 jam dengan garam ikan.',
                'is_featured' => true,
                'image_path' => '/images/bettas/pk-avatargordon.jpg',
            ],
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Black Samurai Grade A+',
                'slug' => 'ikan-cupang-plakat-black-samurai-grade-a',
                'sku' => 'PK-BS-008',
                'price' => 320000,
                'discount_price' => 270000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Black Samurai Platinum Mask',
                'size_cm' => 4.5,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Plakat Black Samurai dengan topeng sisik naga platinum perak tebal menutupi punggung dan kepala menyerupai zirah ksatria samurai Jepang.',
                'care_guide' => 'Berikan pelet berprotein tinggi dan jentik nyamuk agar sisik platinum tetap tebal dan tidak pudar.',
                'is_featured' => true,
                'image_path' => '/images/bettas/pk-blacksamurai.jpg',
            ],
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Hellboy Super Red Dark',
                'slug' => 'ikan-cupang-plakat-hellboy-super-red-dark',
                'sku' => 'PK-HB-009',
                'price' => 280000,
                'discount_price' => 230000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Hellboy Blood Red & Black',
                'size_cm' => 4.4,
                'age_months' => 3.6,
                'care_level' => 'beginner',
                'description' => 'Warna merah darah membara dipadu pola hitam pekat garang khas Hellboy line. Mental tarung sangat aktif dan agresif saat ngedok.',
                'care_guide' => 'Rutin berikan daun ketapang untuk menjaga imunitas dan mempertajam warna merah pekat.',
                'is_featured' => true,
                'image_path' => '/images/bettas/pk-hellboy.jpg',
            ],
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Red Samurai Platinum',
                'slug' => 'ikan-cupang-plakat-red-samurai-platinum',
                'sku' => 'PK-RS-010',
                'price' => 310000,
                'discount_price' => 260000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Red Samurai Platinum Dragon',
                'size_cm' => 4.6,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Kombinasi langka badan merah pekat dengan sisik punggung platinum putih tebal menyerupai helm baja samurai.',
                'care_guide' => 'Ganti air 40% setiap 3 hari sekali menggunakan air bersuhu ruangan stabil.',
                'is_featured' => false,
                'image_path' => '/images/bettas/pk-redsamurai.jpg',
            ],
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Blue Rim Clean Line',
                'slug' => 'ikan-cupang-plakat-blue-rim-clean-line',
                'sku' => 'PK-BR-011',
                'price' => 380000,
                'discount_price' => 320000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Clean White Body & Blue Rim',
                'size_cm' => 4.5,
                'age_months' => 4.2,
                'care_level' => 'intermediate',
                'description' => 'Plakat Blue Rim clean line tanpa noda warna bocor di badan putih susu. Ring biru elektrik rapi dan tebal di tepi sirip.',
                'care_guide' => 'Kualitas air harus sangat terjaga agar warna dasar putih tetap bersih tanpa mutasi bercak kotor.',
                'is_featured' => false,
                'image_path' => '/images/bettas/pk-bluerim.jpg',
            ],
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Super Black Velvet Melano',
                'slug' => 'ikan-cupang-plakat-super-black-velvet',
                'sku' => 'PK-SB-012',
                'price' => 210000,
                'discount_price' => null,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Solid Matte Black Velvet',
                'size_cm' => 4.4,
                'age_months' => 3.5,
                'care_level' => 'beginner',
                'description' => 'Plakat dengan warna hitam pekat doff velvet tanpa pantulan warna lain. Bentuk caudal D-shape rapat dan lincah.',
                'care_guide' => 'Mudah dirawat dan sangat cocok untuk pemula.',
                'is_featured' => false,
                'image_path' => '/images/bettas/pk-superblack.jpg',
            ],

            // --- KOI & NEMO GALAXY ---
            [
                'category_slug' => 'koi-nemo',
                'name' => 'Ikan Cupang Plakat Koi Galaxy 4 Colors',
                'slug' => 'ikan-cupang-plakat-koi-galaxy-4-colors',
                'sku' => 'KG-MC-013',
                'price' => 220000,
                'discount_price' => 185000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Koi Galaxy 4 Colors',
                'size_cm' => 4.3,
                'age_months' => 3.5,
                'care_level' => 'beginner',
                'description' => 'Kombinasi warna merah, oranye, hitam, dan taburan sisik bintang biru berkilau yang menyala di bawah cahaya akuarium.',
                'care_guide' => 'Rutin ganti air 30% setiap 3 hari sekali untuk menjaga kecerahan warna marble koi.',
                'is_featured' => true,
                'image_path' => '/images/bettas/koi-multicolor.jpg',
            ],
            [
                'category_slug' => 'koi-nemo',
                'name' => 'Ikan Cupang Plakat Nemo Tiger Candy Galaxy',
                'slug' => 'ikan-cupang-plakat-nemo-tiger-candy',
                'sku' => 'KG-NT-014',
                'price' => 265000,
                'discount_price' => 225000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Nemo Tiger Candy Stripes',
                'size_cm' => 4.4,
                'age_months' => 3.7,
                'care_level' => 'intermediate',
                'description' => 'Belang harimau oranye-kuning cerah berpadu dengan bercak hitam tegas dan glitter sisik galaksi tembaga.',
                'care_guide' => 'Beri pakan peningkat pigmen karotenoid seperti jentik nyamuk atau udang renik.',
                'is_featured' => false,
                'image_path' => '/images/bettas/koi-nemotiger.jpg',
            ],
            [
                'category_slug' => 'koi-nemo',
                'name' => 'Ikan Cupang Plakat Yellow Fancy Copper',
                'slug' => 'ikan-cupang-plakat-yellow-fancy-copper',
                'sku' => 'KG-YF-015',
                'price' => 210000,
                'discount_price' => 175000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Yellow Fancy Copper Flakes',
                'size_cm' => 4.4,
                'age_months' => 3.5,
                'care_level' => 'beginner',
                'description' => 'Warna dasar kuning segar cerah dengan taburan sisik tembaga berkilau lembut dan sirip transparan menawan.',
                'care_guide' => 'Suhu air ideal 26-29°C dengan soliter terawat.',
                'is_featured' => false,
                'image_path' => '/images/bettas/koi-yellowfancy.jpg',
            ],
            [
                'category_slug' => 'koi-nemo',
                'name' => 'Ikan Cupang Plakat Candy Multicolor Top Grade',
                'slug' => 'ikan-cupang-plakat-candy-multicolor-top-grade',
                'sku' => 'KG-CD-016',
                'price' => 295000,
                'discount_price' => 245000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Pastel Candy Multicolor',
                'size_cm' => 4.5,
                'age_months' => 3.8,
                'care_level' => 'intermediate',
                'description' => 'Gradasi warna pastel manis bagai permen dengan mutasi warna stabil dan bukaan caudal D-shape simetris.',
                'care_guide' => 'Gunakan daun ketapang olahan yang telah disterilkan.',
                'is_featured' => false,
                'image_path' => '/images/bettas/koi-candymulti.jpg',
            ],

            // --- CROWNTAIL (SERIT) ---
            [
                'category_slug' => 'crowntail',
                'name' => 'Ikan Cupang Crowntail King Dragon Copper (Serit)',
                'slug' => 'ikan-cupang-crowntail-king-dragon-copper',
                'sku' => 'CT-KD-017',
                'price' => 180000,
                'discount_price' => 150000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'crowntail',
                'color_pattern' => 'Copper Metallic Double Ray',
                'size_cm' => 5.0,
                'age_months' => 4.2,
                'care_level' => 'beginner',
                'description' => 'Karya asli breeder Slipi Jakarta. Sirip mahkota berduri ganda (Double Ray) kokoh tegap dengan sisik naga tembaga berkilau.',
                'care_guide' => 'Jaga kebersihan air secara ketat agar cabang serit tidak mengeriting atau terkena fin rot.',
                'is_featured' => true,
                'image_path' => '/images/bettas/ct-kingcopper.jpg',
            ],
            [
                'category_slug' => 'crowntail',
                'name' => 'Ikan Cupang Crowntail Black Orchid Double Ray',
                'slug' => 'ikan-cupang-crowntail-black-orchid-double-ray',
                'sku' => 'CT-BO-018',
                'price' => 195000,
                'discount_price' => 165000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'crowntail',
                'color_pattern' => 'Black Orchid Royal Sheen',
                'size_cm' => 5.1,
                'age_months' => 4.5,
                'care_level' => 'beginner',
                'description' => 'Duri sirip hitam pekat anggrek malam dengan pantulan biru safir elektrik di sela-sela duri mahkotanya.',
                'care_guide' => 'Gunakan soliter dengan penyaring lembut agar duri sirip tidak patah.',
                'is_featured' => false,
                'image_path' => '/images/bettas/ct-blackorchid.jpg',
            ],
            [
                'category_slug' => 'crowntail',
                'name' => 'Ikan Cupang Crowntail Royal Blue Mask',
                'slug' => 'ikan-cupang-crowntail-royal-blue-mask',
                'sku' => 'CT-RB-019',
                'price' => 170000,
                'discount_price' => null,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'crowntail',
                'color_pattern' => 'Royal Blue Mask',
                'size_cm' => 4.9,
                'age_months' => 4.0,
                'care_level' => 'beginner',
                'description' => 'Biru laut elektrik menyala dengan kepala gelap tegas dan susunan duri serit lurus sempurna.',
                'care_guide' => 'Berikan pakan hidup jentik atau cacing sutra higienis.',
                'is_featured' => false,
                'image_path' => '/images/bettas/ct-royalblue.jpg',
            ],
            [
                'category_slug' => 'crowntail',
                'name' => 'Ikan Cupang King Crowntail Crossing Rays',
                'slug' => 'ikan-cupang-king-crowntail-crossing-rays',
                'sku' => 'CT-XR-020',
                'price' => 230000,
                'discount_price' => 195000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'crowntail',
                'color_pattern' => 'King Crowntail Crossing Ray',
                'size_cm' => 5.2,
                'age_months' => 4.8,
                'care_level' => 'intermediate',
                'description' => 'Tipe King Crowntail paling langka di mana jari-jari sirip saling menyilang (cross) membentuk anyaman mahkota megah.',
                'care_guide' => 'Ekstrak daun ketapang wajib ada di soliter untuk menjaga kelenturan jari-jari sirip silang.',
                'is_featured' => false,
                'image_path' => '/images/bettas/ct-crossray.jpg',
            ],

            // --- GIANT BETTA ---
            [
                'category_slug' => 'giant',
                'name' => 'Ikan Cupang Giant Plakat Nemo Candy BO 6.2 cm',
                'slug' => 'ikan-cupang-giant-plakat-nemo-candy-bo-6cm',
                'sku' => 'GT-NC-021',
                'price' => 450000,
                'discount_price' => 395000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'giant',
                'color_pattern' => 'Nemo Candy Multi',
                'size_cm' => 6.2,
                'age_months' => 5.5,
                'care_level' => 'advanced',
                'description' => 'Cupang Giant jumbo tebal dengan panjang tubuh murni (Body Only) 6.2 cm. Nafsu makan luar biasa rakus dan berotot kekar.',
                'care_guide' => 'Wajib soliter besar minimal 20x20x25 cm agar leluasa berenang dan berkembang maksimal.',
                'is_featured' => true,
                'image_path' => '/images/bettas/gt-nemocandy.jpg',
            ],
            [
                'category_slug' => 'giant',
                'name' => 'Ikan Cupang Giant Plakat Super Red BO 6.5 cm',
                'slug' => 'ikan-cupang-giant-plakat-super-red-bo-6-5cm',
                'sku' => 'GT-SR-022',
                'price' => 420000,
                'discount_price' => 360000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'giant',
                'color_pattern' => 'Solid Giant Super Red',
                'size_cm' => 6.5,
                'age_months' => 6.0,
                'care_level' => 'advanced',
                'description' => 'Ukuran jumbo raksasa 6.5 cm dengan warna merah membara solid. Postur tubuh kokoh dengan sirip proporsional.',
                'care_guide' => 'Beri pakan berprotein tinggi 2-3 kali sehari porsi proporsional.',
                'is_featured' => false,
                'image_path' => '/images/bettas/gt-superred.jpg',
            ],
            [
                'category_slug' => 'giant',
                'name' => 'Ikan Cupang Giant Plakat Avatar Copper BO 6.0 cm',
                'slug' => 'ikan-cupang-giant-plakat-avatar-copper-bo-6cm',
                'sku' => 'GT-AC-023',
                'price' => 480000,
                'discount_price' => 420000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'giant',
                'color_pattern' => 'Giant Avatar Copper Metallic',
                'size_cm' => 6.0,
                'age_months' => 5.2,
                'care_level' => 'advanced',
                'description' => 'Perpaduan genetik langka: ukuran tubuh Giant raksasa dipadukan corak eksotis Avatar Copper bertotol tembaga biru elektrik.',
                'care_guide' => 'Wadah soliter minimal 8 liter air dengan aerasi halus atau penggantian air teratur.',
                'is_featured' => false,
                'image_path' => '/images/bettas/gt-avatarcopper.jpg',
            ],

            // --- DOUBLE TAIL ---
            [
                'category_slug' => 'double-tail',
                'name' => 'Ikan Cupang Double Tail Rose Tail Super Red',
                'slug' => 'ikan-cupang-double-tail-rose-tail-super-red',
                'sku' => 'DT-SR-024',
                'price' => 280000,
                'discount_price' => 235000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'double_tail',
                'color_pattern' => 'Solid Super Red Rose Tail',
                'size_cm' => 4.6,
                'age_months' => 3.8,
                'care_level' => 'intermediate',
                'description' => 'Sirip ekor terbelah dua simetris (cagak) dengan ujung melipat menyerupai kelopak bunga mawar mekar merah pekat.',
                'care_guide' => 'Gunakan daun ketapang tua agar sirip tetap lentur dan tidak mudah sobek saat bergerak.',
                'is_featured' => true,
                'image_path' => '/images/bettas/dt-rosetail.jpg',
            ],
            [
                'category_slug' => 'double-tail',
                'name' => 'Ikan Cupang Double Tail Plakat Fancy Copper',
                'slug' => 'ikan-cupang-double-tail-plakat-fancy-copper',
                'sku' => 'DT-FC-025',
                'price' => 250000,
                'discount_price' => 210000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'double_tail',
                'color_pattern' => 'Fancy Copper Dual Caudal',
                'size_cm' => 4.4,
                'age_months' => 3.6,
                'care_level' => 'intermediate',
                'description' => 'Plakat berekor pendek dengan dua belahan ekor terpisah rapi serta dorsal punggung ekstra lebar.',
                'care_guide' => 'Rutin ganti air dan berikan pakan hidup bernutrisi.',
                'is_featured' => false,
                'image_path' => '/images/bettas/dt-fancycopper.jpg',
            ],

            // --- DUMBO EAR ---
            [
                'category_slug' => 'dumbo-ear',
                'name' => 'Ikan Cupang Dumbo Ear Lavender Halfmoon Grade A',
                'slug' => 'ikan-cupang-dumbo-ear-lavender-halfmoon',
                'sku' => 'DE-LV-026',
                'price' => 310000,
                'discount_price' => 260000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Lavender & White Big Ear',
                'size_cm' => 4.7,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Sirip dayung dada (pectoral) melebar putih besar seperti telinga gajah, berkibar anggun saat berenang.',
                'care_guide' => 'Pastikan arus air tenang agar tidak mengganggu pergerakan sirip dada yang lebar.',
                'is_featured' => true,
                'image_path' => '/images/bettas/de-lavender.jpg',
            ],
            [
                'category_slug' => 'dumbo-ear',
                'name' => 'Ikan Cupang Dumbo Ear Plakat Salamander',
                'slug' => 'ikan-cupang-dumbo-ear-plakat-salamander',
                'sku' => 'DE-SL-027',
                'price' => 275000,
                'discount_price' => null,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Salamander Purple Pink Big Ear',
                'size_cm' => 4.5,
                'age_months' => 3.8,
                'care_level' => 'intermediate',
                'description' => 'Plakat lincah berkuping gajah lebar warna putih susu dengan perpaduan warna badan ungu salamander menawan.',
                'care_guide' => 'Gunakan air endapan dengan pH seimbang 6.8-7.2.',
                'is_featured' => false,
                'image_path' => '/images/bettas/de-salamander.jpg',
            ],

            // --- ALIEN & WILD HYBRID ---
            [
                'category_slug' => 'alien-wild',
                'name' => 'Ikan Cupang Alien Green Hybrid Wild Betta',
                'slug' => 'ikan-cupang-alien-green-hybrid-wild-betta',
                'sku' => 'WL-AL-028',
                'price' => 290000,
                'discount_price' => 245000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Emerald Alien Green Metallic',
                'size_cm' => 4.6,
                'age_months' => 4.5,
                'care_level' => 'intermediate',
                'description' => 'Hibrida cupang alam liar (Mahachai x Smaragdina) dengan pola jaring sisik hijau zamrud metalik yang sangat berkilau.',
                'care_guide' => 'Wajib wadah tertutup rapat karena cupang alien sangat aktif dan pandai melompat tinggi.',
                'is_featured' => true,
                'image_path' => '/images/bettas/wl-aliengreen.jpg',
            ],
            [
                'category_slug' => 'alien-wild',
                'name' => 'Ikan Cupang Alien Copper Hybrid Wild Betta',
                'slug' => 'ikan-cupang-alien-copper-hybrid-wild-betta',
                'sku' => 'WL-AC-029',
                'price' => 310000,
                'discount_price' => 265000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Copper Wild Net Scales',
                'size_cm' => 4.7,
                'age_months' => 4.6,
                'care_level' => 'intermediate',
                'description' => 'Cupang alien dengan kilau tembaga metalik liar dan bentuk kepala lancip khas cupang rawa alami.',
                'care_guide' => 'Beri pakan hidup alami seperti kutu air dan jentik.',
                'is_featured' => false,
                'image_path' => '/images/bettas/wl-aliencopper.jpg',
            ],

            // --- SPESIMEN KONTES & INDUKAN ---
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Plakat Avatar Gordon High Grade Line',
                'slug' => 'plakat-avatar-gordon-high-grade-line',
                'sku' => 'PR-AG-030',
                'price' => 550000,
                'discount_price' => 480000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Avatar Gordon Contest Line',
                'size_cm' => 4.5,
                'age_months' => 4.5,
                'care_level' => 'advanced',
                'description' => 'Spesimen Plakat Avatar Gordon kualitas kontes pilihan. Form sirip proporsional, mutiara sisik menyala, dan mental flaring sangat agresif.',
                'care_guide' => 'Pelihara dalam soliter kaca 20x15x15 cm dengan daun ketapang tua dan pakan hidup kaya nutrisi.',
                'is_featured' => true,
                'image_path' => '/images/bettas/pr-avatargordon.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Betina (Female) Halfmoon Blue Rim Full Egg Siap Pijah',
                'slug' => 'betina-female-halfmoon-blue-rim-full-egg',
                'sku' => 'FM-BR-031',
                'price' => 190000,
                'discount_price' => 160000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Blue Rim Female Breeder',
                'size_cm' => 4.2,
                'age_months' => 4.2,
                'care_level' => 'intermediate',
                'description' => 'Indukan betina Halfmoon Blue Rim perut buncit terisi penuh sel telur. Siap dikawinkan dengan pejantan pilihan Anda.',
                'care_guide' => 'Berikan jentik nyamuk dan cacing sutra untuk mematangkan sel telur sebelum disatukan dengan jantan.',
                'is_featured' => false,
                'image_path' => '/images/bettas/fm-bluerim.jpg',
            ],
            [
                'category_slug' => 'crowntail',
                'name' => 'Ikan Cupang Betina (Female) Crowntail King Dragon Serit Siap Pijah',
                'slug' => 'betina-female-crowntail-king-dragon-serit-siap-pijah',
                'sku' => 'CT-FM-032',
                'price' => 160000,
                'discount_price' => 135000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'crowntail',
                'color_pattern' => 'Copper Dragon Ray Female',
                'size_cm' => 4.4,
                'age_months' => 4.2,
                'care_level' => 'intermediate',
                'description' => 'Indukan betina Crowntail (Serit) genetik King Dragon Copper. Sirip serit rapi dan perut buncit terisi telur matang, siap dicelupkan untuk kawin.',
                'care_guide' => 'Suhu ideal 27-29°C dengan air endapan daun ketapang untuk kenyamanan pemijahan.',
                'is_featured' => false,
                'image_path' => '/images/bettas/ct-kingcopper.jpg',
            ],
            [
                'category_slug' => 'crowntail',
                'name' => 'Ikan Cupang Crowntail Black Orchid Double Ray Grade A',
                'slug' => 'crowntail-black-orchid-double-ray-grade-a',
                'sku' => 'CT-PR-033',
                'price' => 380000,
                'discount_price' => 320000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'crowntail',
                'color_pattern' => 'Black Orchid Double Ray',
                'size_cm' => 5.0,
                'age_months' => 4.5,
                'care_level' => 'intermediate',
                'description' => 'Pejantan Crowntail Black Orchid pilihan kontes. Karakter warna hitam pekat elegan dengan duri sirip serit ganda (double ray) mekar rapi tanpa cacat.',
                'care_guide' => 'Wadah soliter minimal 4 liter air tenang dengan daun ketapang olahan dan garam ikan.',
                'is_featured' => true,
                'image_path' => '/images/bettas/ct-blackorchid.jpg',
            ],
            [
                'category_slug' => 'plakat',
                'name' => 'Ikan Cupang Betina (Female) Plakat Black Samurai Grade A+ Full Egg',
                'slug' => 'betina-female-plakat-black-samurai-grade-a',
                'sku' => 'PK-FM-034',
                'price' => 210000,
                'discount_price' => 175000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'plakat',
                'color_pattern' => 'Black Samurai Platinum Helmet Female',
                'size_cm' => 4.3,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Indukan betina Black Samurai dengan zirah sisik platinum tebal menutupi dorsal dan badan hitam pekat. Titik putih telur (ovipositor) sudah sangat jelas.',
                'care_guide' => 'Kondisikan dengan pakan jentik nyamuk atau cacing darah beku.',
                'is_featured' => false,
                'image_path' => '/images/bettas/pk-blacksamurai.jpg',
            ],
            [
                'category_slug' => 'koi-nemo',
                'name' => 'Ikan Cupang Betina (Female) Plakat Koi Galaxy Multi Full Telur',
                'slug' => 'betina-female-plakat-koi-galaxy-multi-full-telur',
                'sku' => 'KG-FM-035',
                'price' => 220000,
                'discount_price' => 185000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'plakat',
                'color_pattern' => 'Koi Galaxy 4 Colors Female Breeder',
                'size_cm' => 4.2,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Indukan Plakat Koi Galaxy dengan sebaran warna merah, hitam, kuning, dan sisik mutiara biru berkilau. Perut buncit siap membuahkan burayak grade juara.',
                'care_guide' => 'Beri pakan hidup kaya nutrisi dan jaga suhu air stabil 28°C.',
                'is_featured' => false,
                'image_path' => '/images/bettas/koi-candymulti.jpg',
            ],
            [
                'category_slug' => 'koi-nemo',
                'name' => 'Ikan Cupang Plakat Koi Nemo Tiger Candy Galaxy Special Grade',
                'slug' => 'plakat-koi-nemo-tiger-candy-galaxy-special-grade',
                'sku' => 'KG-PR-036',
                'price' => 580000,
                'discount_price' => 495000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'plakat',
                'color_pattern' => 'Nemo Tiger Galaxy Multicolor',
                'size_cm' => 4.5,
                'age_months' => 4.2,
                'care_level' => 'advanced',
                'description' => 'Spesimen Koi Nemo Tiger Galaxy genetik unggulan. Corak loreng harimau kontras dengan taburan sisik galaksi mutiara mengkilap di badan.',
                'care_guide' => 'Beri pakan hidup kaya nutrisi dan jaga suhu air stabil 27-29°C untuk mutasi warna maksimal.',
                'is_featured' => true,
                'image_path' => '/images/bettas/koi-nemotiger.jpg',
            ],
            [
                'category_slug' => 'giant',
                'name' => 'Ikan Cupang Betina (Female) Giant Plakat Nemo Candy BO 5.5 cm',
                'slug' => 'betina-female-giant-plakat-nemo-candy-bo-5-5-cm',
                'sku' => 'GT-FM-037',
                'price' => 320000,
                'discount_price' => 275000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'giant',
                'color_pattern' => 'Giant Nemo Candy Multicolor Female',
                'size_cm' => 5.5,
                'age_months' => 5.0,
                'care_level' => 'advanced',
                'description' => 'Indukan cupang raksasa Giant Betina BO 5.5 cm dengan corak Nemo Candy cerah. Tulangan tebal, perut buncit full telur ribuan butir.',
                'care_guide' => 'Wadah pembesaran dan perkawinan minimal 15-20 liter air karena ukuran badan yang besar.',
                'is_featured' => false,
                'image_path' => '/images/bettas/gt-nemocandy.jpg',
            ],
            [
                'category_slug' => 'giant',
                'name' => 'Ikan Cupang Giant Plakat Super Red BO 6.3 cm Grade Kontes',
                'slug' => 'giant-plakat-super-red-bo-6-3-cm-grade-kontes',
                'sku' => 'GT-PR-038',
                'price' => 750000,
                'discount_price' => 650000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'giant',
                'color_pattern' => 'Giant Super Red Bloodline',
                'size_cm' => 6.3,
                'age_months' => 5.5,
                'care_level' => 'advanced',
                'description' => 'Spesimen Giant Super Red kelas berat dengan tulangan ekstra kokoh. Ukuran Body Only (BO) 6.3 cm dengan warna merah merona pekat tanpa noda hitam.',
                'care_guide' => 'Wadah soliter pembesaran minimal 10-15 liter air dengan pakan udang renik dan pelet kaya protein.',
                'is_featured' => true,
                'image_path' => '/images/bettas/gt-superred.jpg',
            ],
            [
                'category_slug' => 'double-tail',
                'name' => 'Ikan Cupang Betina (Female) Double Tail Rose Tail Super Red',
                'slug' => 'betina-female-double-tail-rose-tail-super-red',
                'sku' => 'DT-FM-039',
                'price' => 210000,
                'discount_price' => 175000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'double_tail',
                'color_pattern' => 'Super Red Dual Caudal Female',
                'size_cm' => 4.3,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Indukan betina Double Tail (Cagak) dengan dua belahan ekor simetris dan dorsal lebar. Perut buncit terisi penuh sel telur merah.',
                'care_guide' => 'Gunakan air rendaman ketapang lembut dan garam ikan.',
                'is_featured' => false,
                'image_path' => '/images/bettas/dt-rosetail.jpg',
            ],
            [
                'category_slug' => 'dumbo-ear',
                'name' => 'Ikan Cupang Betina (Female) Dumbo Ear Big Ear Platinum White',
                'slug' => 'betina-female-dumbo-ear-big-ear-platinum-white',
                'sku' => 'DE-FM-040',
                'price' => 230000,
                'discount_price' => 190000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'White Platinum Big Ear Female',
                'size_cm' => 4.3,
                'age_months' => 4.0,
                'care_level' => 'intermediate',
                'description' => 'Indukan Dumbo Ear telinga gajah putih bersih melebar anggun. Telur matang di perut siap dikawinkan.',
                'care_guide' => 'Air tenang tanpa arus kencang agar sirip dayung tetap terawat mulus.',
                'is_featured' => false,
                'image_path' => '/images/bettas/de-lavender.jpg',
            ],
            [
                'category_slug' => 'alien-wild',
                'name' => 'Ikan Cupang Betina (Female) Alien Green Hybrid Wild Betta Siap Pijah',
                'slug' => 'betina-female-alien-green-hybrid-wild-betta',
                'sku' => 'WL-FM-041',
                'price' => 250000,
                'discount_price' => 210000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'female',
                'betta_type' => 'plakat',
                'color_pattern' => 'Wild Emerald Net Scale Female',
                'size_cm' => 4.4,
                'age_months' => 4.5,
                'care_level' => 'intermediate',
                'description' => 'Indukan cupang liar hibrida Alien Green dengan kilau zamrud menawan. Fisik lincah, tangguh, dan sudah buncit telur.',
                'care_guide' => 'Tutup rapat wadah dan beri tanaman air seperti frogbit.',
                'is_featured' => false,
                'image_path' => '/images/bettas/wl-aliengreen.jpg',
            ],
            [
                'category_slug' => 'halfmoon',
                'name' => 'Ikan Cupang Halfmoon Super Red Solid Bukaan 180 Derajat',
                'slug' => 'halfmoon-super-red-solid-bukaan-180-derajat',
                'sku' => 'HM-PR-042',
                'price' => 450000,
                'discount_price' => 385000,
                'stock' => 1,
                'status' => 'available',
                'gender' => 'male',
                'betta_type' => 'halfmoon',
                'color_pattern' => 'Super Red Solid 180 Degree',
                'size_cm' => 4.8,
                'age_months' => 4.2,
                'care_level' => 'intermediate',
                'description' => 'Pejantan Halfmoon Super Red dengan ekor bukaan 180 derajat mekar sempurna tanpa celah. Warna merah cabai merata dari kepala hingga ujung sirip.',
                'care_guide' => 'Jaga kebersihan air secara berkala dengan siphon kotoran dan beri sekat soliter agar ekor tidak robek.',
                'is_featured' => true,
                'image_path' => '/images/bettas/hm-superred.jpg',
            ],
        ];

        // Clean any old products
        $allowedSkus = array_column($productsData, 'sku');
        Product::whereNotIn('sku', $allowedSkus)->delete();
        ProductImage::truncate();

        foreach ($productsData as $pData) {
            $cat = $categories[$pData['category_slug']] ?? null;
            if (! $cat) {
                continue;
            }

            $imagePath = $pData['image_path'];
            unset($pData['category_slug'], $pData['image_path']);
            $pData['category_id'] = $cat->id;

            $product = Product::updateOrCreate(['sku' => $pData['sku']], $pData);

            // Create primary product image
            ProductImage::create([
                'product_id' => $product->id,
                'image_url' => $imagePath,
                'is_primary' => true,
                'sort_order' => 1,
            ]);
        }

        // 6. Seed Article Categories
        $artCatsData = [
            ['name' => 'Panduan Perawatan Cupang', 'slug' => 'panduan-perawatan', 'description' => 'Tips cara merawat ikan cupang sehari-hari agar sehat, lincah, dan berumur panjang.'],
            ['name' => 'Pakan & Nutrisi Betta', 'slug' => 'pakan-nutrisi-artikel', 'description' => 'Ulasan makanan hidup vs pelet serta cara menaikkan warna spesimen cupang.'],
            ['name' => 'Penyakit & Obat Cupang', 'slug' => 'penyakit-obat', 'description' => 'Gejala penyakit umum cupang seperti fin rot, jamur, dropsy, dan penanganannya.'],
            ['name' => 'Breeding & Budidaya Cupang', 'slug' => 'breeding-cupang', 'description' => 'Langkah-langkah membudidayakan ikan cupang dari perjodohan hingga pembesaran burayak.'],
        ];

        $artCats = [];
        foreach ($artCatsData as $ac) {
            $artCats[$ac['slug']] = ArticleCategory::updateOrCreate(['slug' => $ac['slug']], $ac);
        }

        // 7. Seed Articles with Cross-Selling Betta Products
        $articlesData = [
            [
                'cat_slug' => 'panduan-perawatan',
                'title' => 'Cara Merawat Ikan Cupang untuk Pemula: Panduan Lengkap',
                'slug' => 'cara-merawat-ikan-cupang-untuk-pemula',
                'excerpt' => 'Panduan lengkap mulai dari memilih wadah soliter aquarium cupang, cara menyiapkan air endapan ketapang, hingga jadwal pemberian makan yang tepat.',
                'reading_time_minutes' => 6,
                'featured_image' => '/images/hero-betta.jpg',
                'content' => '<h2>1. Persiapan Wadah Soliter yang Tepat</h2><p>Mitos bahwa ikan cupang bisa hidup bahagia di wadah toples sempit harus dihindari. Sediakan soliter kaca minimal ukuran 15x15x20 cm agar cupang dapat berenang leluasa dan mengembangkan siripnya dengan baik.</p><h2>2. Kualitas Air adalah Kunci</h2><p>Gunakan air tawar yang sudah diendapkan minimal 24 jam untuk menghilangkan kaporit. Tambahkan ekstrak daun ketapang olahan dan sedikit garam ikan untuk menjaga stabilitas pH di angka 6.5 - 7.5.</p><h2>3. Jadwal dan Porsi Makan</h2><p>Ikan cupang rentan terhadap perut kembung (*bloat*). Berikan pakan secukupnya 1 hingga 2 kali sehari dalam porsi kecil yang habis dalam 2 menit.</p>',
                'related_sku' => ['HM-BR-001', 'PK-AV-007'],
            ],
            [
                'cat_slug' => 'penyakit-obat',
                'title' => 'Mengenal Gejala Fin Rot pada Cupang dan Cara Mengobatinya',
                'slug' => 'gejala-fin-rot-cupang-dan-pengobatannya',
                'excerpt' => 'Fin rot atau busuk sirip adalah musuh utama ikan cupang. Kenali tanda-tanda awal dan langkah penyelamatannya sebelum sirip indah cupang Anda rusak.',
                'reading_time_minutes' => 5,
                'featured_image' => '/images/categories/crowntail.jpg',
                'content' => '<h2>Apa itu Fin Rot pada Cupang?</h2><p>Fin rot disebabkan oleh infeksi bakteri akibat air kotor atau stres lingkungan. Ujung sirip cupang tampak compang-camping, menghitam, atau memutih seperti terbakar.</p><h2>Langkah Pengobatan Intensif</h2><p>1. Karantina ikan cupang di wadah terpisah dengan air baru yang bersih.<br>2. Berikan obat khusus ikan atau methylene blue serta daun ketapang pekat.<br>3. Ganti air 50% setiap hari sampai tunas sirip baru mulai tumbuh.</p>',
                'related_sku' => ['CT-KD-017', 'HM-MG-003'],
            ],
            [
                'cat_slug' => 'panduan-perawatan',
                'title' => 'Perbedaan Karakteristik Cupang Plakat, Halfmoon, dan Crowntail',
                'slug' => 'perbedaan-karakteristik-cupang-plakat-halfmoon-crowntail',
                'excerpt' => 'Pelajari karakteristik visual dan tingkat kesulitan perawatan dari 3 jenis ikan cupang paling populer di dunia kontes.',
                'reading_time_minutes' => 5,
                'featured_image' => '/images/categories/plakat.jpg',
                'content' => '<h2>1. Cupang Halfmoon (HM)</h2><p>Dikenal dengan bukaan sirip ekor 180 derajat menyerupai bulan sabit. Sangat memukau namun membutuhkan perhatian ekstra terhadap kebersihan air agar sirip lebarnya tidak sobek atau menggulung.</p><h2>2. Cupang Plakat (PK)</h2><p>Memiliki sirip ekor pendek yang lincah dan berotot. Lebih tahan banting, mudah dirawat, dan memiliki varian corak mutasi yang sangat atraktif seperti Samurai, Avatar, dan Koi.</p><h2>3. Cupang Crowntail (CT / Serit)</h2><p>Karya asli breeder Indonesia yang diakui dunia internasional. Siripnya menyerupai mahkota berduri dengan tulang sirip menjuntai artistik.</p>',
                'related_sku' => ['KG-MC-013', 'PK-BS-008'],
            ],
        ];

        Article::whereNotIn('slug', array_column($articlesData, 'slug'))->delete();

        foreach ($articlesData as $artData) {
            $cat = $artCats[$artData['cat_slug']] ?? null;
            if (! $cat) {
                continue;
            }

            $relatedSkus = $artData['related_sku'];
            unset($artData['cat_slug'], $artData['related_sku']);

            $article = Article::updateOrCreate(
                ['slug' => $artData['slug']],
                array_merge($artData, [
                    'author_id' => $admin->id,
                    'category_id' => $cat->id,
                    'status' => 'published',
                    'published_at' => now(),
                    'views_count' => rand(120, 850),
                    'meta_title' => $artData['title'].' | Pamulang Fish Store',
                    'meta_description' => $artData['excerpt'],
                ])
            );

            // Attach related cross-selling products
            $productsToSync = [];
            foreach ($relatedSkus as $idx => $sku) {
                $p = Product::where('sku', $sku)->first();
                if ($p) {
                    $productsToSync[$p->id] = ['sort_order' => $idx];
                }
            }
            if (! empty($productsToSync)) {
                $article->relatedProducts()->sync($productsToSync);
            }
        }

        // 7. Seed Realistic Live Animal Orders (Pertemuan 8, 10, 11)
        $ordersData = [
            [
                'order_number' => 'BTC-20260928-89211',
                'user_id' => $customer->id,
                'customer_name' => 'Budi Santoso',
                'customer_email' => 'customer@pamulangfish.com',
                'customer_phone' => '089876543210',
                'shipping_province' => 'Banten',
                'shipping_city' => 'Tangerang Selatan',
                'shipping_district' => 'Pamulang',
                'shipping_address' => 'Jl. Pajajaran No. 12, RT 02/RW 04, Pamulang Barat',
                'shipping_postal_code' => '15417',
                'shipping_courier' => 'JNE YES (Yakin Esok Sampai - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 439000,
                'shipping_cost' => 35000,
                'discount' => 0,
                'total_amount' => 474000,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'paid',
                'order_status' => 'delivered',
                'tracking_number' => 'JNE-YES-8829104812',
                'notes' => 'Packing styrofoam tebal + tabung oksigen prima. Ikan sampai sangat sehat.',
                'created_at' => now()->subDays(12),
                'items' => [
                    ['sku' => 'HM-BR-001', 'qty' => 1],
                    ['sku' => 'PK-BS-008', 'qty' => 1],
                ],
            ],
            [
                'order_number' => 'BTC-20261001-44102',
                'user_id' => null,
                'customer_name' => 'Hendra Wijaya',
                'customer_email' => 'hendra.wijaya@gmail.com',
                'customer_phone' => '081288339911',
                'shipping_province' => 'DKI Jakarta',
                'shipping_city' => 'Jakarta Selatan',
                'shipping_district' => 'Cilandak',
                'shipping_address' => 'Jl. Fatmawati Raya No. 45, Cilandak Barat',
                'shipping_postal_code' => '12430',
                'shipping_courier' => 'TIKI ONS (Over Night Services - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 285000,
                'shipping_cost' => 30000,
                'discount' => 0,
                'total_amount' => 315000,
                'payment_method' => 'qris',
                'payment_status' => 'paid',
                'order_status' => 'delivered',
                'tracking_number' => 'TIKI-ONS-9938172635',
                'notes' => 'Video unboxing telah dikirimkan, ikan lincah dan langsung makan.',
                'created_at' => now()->subDays(6),
                'items' => [
                    ['sku' => 'KG-MC-013', 'qty' => 1],
                ],
            ],
            [
                'order_number' => 'BTC-20261003-77291',
                'user_id' => null,
                'customer_name' => 'Siti Rahmawati',
                'customer_email' => 'siti.rahma@yahoo.com',
                'customer_phone' => '081377221100',
                'shipping_province' => 'Jawa Barat',
                'shipping_city' => 'Bandung',
                'shipping_district' => 'Coblong',
                'shipping_address' => 'Jl. Dago Asri No. 18, Dago',
                'shipping_postal_code' => '40135',
                'shipping_courier' => 'JNE YES (Yakin Esok Sampai - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 240000,
                'shipping_cost' => 38000,
                'discount' => 0,
                'total_amount' => 278000,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'paid',
                'order_status' => 'shipped',
                'tracking_number' => 'JNE-YES-7718290312',
                'notes' => 'Ikan sedang meluncur dalam perjalanan kurir kilat menuju Bandung.',
                'created_at' => now()->subDays(2),
                'items' => [
                    ['sku' => 'CT-BO-018', 'qty' => 1],
                ],
            ],
            [
                'order_number' => 'BTC-20261004-91823',
                'user_id' => null,
                'customer_name' => 'Dimas Aditya',
                'customer_email' => 'dimas.aditya@outlook.com',
                'customer_phone' => '085711223344',
                'shipping_province' => 'DI Yogyakarta',
                'shipping_city' => 'Sleman',
                'shipping_district' => 'Depok',
                'shipping_address' => 'Jl. Kaliurang KM 5.5, Gg. Megatruh No. 9',
                'shipping_postal_code' => '55281',
                'shipping_courier' => 'TIKI ONS (Over Night Services - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 395000,
                'shipping_cost' => 45000,
                'discount' => 0,
                'total_amount' => 440000,
                'payment_method' => 'qris',
                'payment_status' => 'paid',
                'order_status' => 'packing',
                'tracking_number' => null,
                'notes' => 'Proses pengisian tabung oksigen dan insulasi styrofoam tebal 3 cm.',
                'created_at' => now()->subHours(24),
                'items' => [
                    ['sku' => 'GT-NC-021', 'qty' => 1],
                ],
            ],
            [
                'order_number' => 'BTC-20261005-55194',
                'user_id' => null,
                'customer_name' => 'Reza Pratama',
                'customer_email' => 'reza.pratama@gmail.com',
                'customer_phone' => '081988776655',
                'shipping_province' => 'Jawa Timur',
                'shipping_city' => 'Surabaya',
                'shipping_district' => 'Gubeng',
                'shipping_address' => 'Jl. Dharmahusada Indah Blok B No. 12',
                'shipping_postal_code' => '60285',
                'shipping_courier' => 'JNE YES (Yakin Esok Sampai - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 260000,
                'shipping_cost' => 42000,
                'discount' => 0,
                'total_amount' => 302000,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'paid',
                'order_status' => 'fish_preparation',
                'tracking_number' => null,
                'notes' => 'Ikan sedang dipuasakan & karantina 24 jam sebelum terbang kilat ke Surabaya.',
                'created_at' => now()->subHours(14),
                'items' => [
                    ['sku' => 'DE-LV-026', 'qty' => 1],
                ],
            ],
            [
                'order_number' => 'BTC-20261006-22819',
                'user_id' => $customer->id,
                'customer_name' => 'Budi Santoso',
                'customer_email' => 'customer@pamulangfish.com',
                'customer_phone' => '089876543210',
                'shipping_province' => 'Banten',
                'shipping_city' => 'Tangerang Selatan',
                'shipping_district' => 'Pamulang',
                'shipping_address' => 'Jl. Pajajaran No. 12, Pamulang Barat',
                'shipping_postal_code' => '15417',
                'shipping_courier' => 'JNE YES (Yakin Esok Sampai - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 480000,
                'shipping_cost' => 35000,
                'discount' => 0,
                'total_amount' => 515000,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'paid',
                'order_status' => 'payment_confirmed',
                'tracking_number' => null,
                'notes' => 'Bukti transfer BCA terverifikasi admin. Bersiap masuk ruang karantina.',
                'created_at' => now()->subHours(3),
                'items' => [
                    ['sku' => 'PR-AG-030', 'qty' => 1],
                ],
            ],
            [
                'order_number' => 'BTC-20261006-88310',
                'user_id' => $customer->id,
                'customer_name' => 'Budi Santoso',
                'customer_email' => 'customer@pamulangfish.com',
                'customer_phone' => '089876543210',
                'shipping_province' => 'Banten',
                'shipping_city' => 'Tangerang Selatan',
                'shipping_district' => 'Pamulang',
                'shipping_address' => 'Jl. Pajajaran No. 12, Pamulang Barat',
                'shipping_postal_code' => '15417',
                'shipping_courier' => 'JNE YES (Yakin Esok Sampai - Khusus Hewan Hidup)',
                'special_live_fish_packing' => true,
                'subtotal' => 245000,
                'shipping_cost' => 35000,
                'discount' => 0,
                'total_amount' => 280000,
                'payment_method' => 'bank_transfer',
                'payment_status' => 'pending',
                'order_status' => 'received',
                'tracking_number' => null,
                'notes' => 'Menunggu unggah bukti transfer pembayaran.',
                'created_at' => now()->subMinutes(45),
                'items' => [
                    ['sku' => 'WL-AL-028', 'qty' => 1],
                ],
            ],
        ];

        foreach ($ordersData as $oData) {
            $itemsData = $oData['items'];
            $createdAt = $oData['created_at'];
            unset($oData['items'], $oData['created_at']);

            $order = Order::updateOrCreate(
                ['order_number' => $oData['order_number']],
                $oData
            );
            $order->created_at = $createdAt;
            $order->save();

            // Clear old items and insert fresh
            $order->items()->delete();
            foreach ($itemsData as $itemInfo) {
                $product = Product::where('sku', $itemInfo['sku'])->first();
                if ($product) {
                    $price = $product->final_price ?? $product->price;
                    OrderItem::create([
                        'order_id' => $order->id,
                        'product_id' => $product->id,
                        'product_name' => $product->name,
                        'product_sku' => $product->sku,
                        'price' => $price,
                        'quantity' => $itemInfo['qty'],
                        'subtotal' => $price * $itemInfo['qty'],
                    ]);
                }
            }
        }

        // 8. Seed Customer Reviews (Pertemuan 10)
        $reviewsData = [
            [
                'sku' => 'HM-BR-001',
                'rating' => 5,
                'review' => 'Spesimen tiba dalam kondisi sangat sehat dan prima! Bukaan sirip 180 derajat sempurna sesuai foto WYSIWYG. Packing tabung oksigen & styrofoam tebal sangat aman. Seller sangat recommended!',
            ],
            [
                'sku' => 'PK-BS-008',
                'rating' => 5,
                'review' => 'Black Samurai-nya jos gandos! Sisik mutiaranya tebal dan mental ngedoknya garang langsung mau flaring pas didekatkan soliter sebelah. Terimakasih Pamulang Fish!',
            ],
            [
                'sku' => 'KG-MC-013',
                'rating' => 5,
                'review' => 'Warna koi candy multi sangat cerah, corak persis seperti yang ada di katalog. Garansi hidup aman dan ekspedisi kilat sampai esok harinya tanpa lecet sedikitpun.',
            ],
            [
                'sku' => 'CT-BO-018',
                'rating' => 5,
                'review' => 'Crowntail Black Orchid sirip seritnya rapi dan tidak ada yang rontok. Karakter warnanya hitam legam elegan.',
            ],
            [
                'sku' => 'PR-AG-030',
                'rating' => 5,
                'review' => 'Plakat Avatar Gordon kualitas kontes mantap! Sisik mutiaranya rapi mengkilap dan mentalnya luar biasa garang saat flaring. Puas banget!',
            ],
            [
                'sku' => 'GT-NC-021',
                'rating' => 4,
                'review' => 'Ukuran jumbo beneran 6.2 cm BO, tulangan tebal dan nafsu makannya luar biasa rakus. Puas belanja di sini!',
            ],
        ];

        Review::truncate();
        foreach ($reviewsData as $rev) {
            $product = Product::where('sku', $rev['sku'])->first();
            if ($product) {
                Review::create([
                    'user_id' => $customer->id,
                    'product_id' => $product->id,
                    'rating' => $rev['rating'],
                    'review' => $rev['review'],
                    'status' => 'approved',
                ]);
            }
        }
    }
}
