<?php

/**
 * Generate professional photo placeholders for betta fish products.
 * Uses GD library to create attractive gradient cards with fish type and color info.
 * Run: php generate_photo_placeholders.php
 */
$bettas = [
    // Halfmoon
    ['file' => 'hm-mustardgas', 'label' => 'Halfmoon Mustard Gas', 'colors' => [[25, 45, 120], [210, 180, 50]]],
    ['file' => 'hm-whiteplatinum', 'label' => 'Halfmoon White Platinum', 'colors' => [[200, 210, 225], [150, 170, 200]]],
    ['file' => 'hm-copperblack', 'label' => 'Halfmoon Copper Black', 'colors' => [[40, 20, 10], [180, 120, 60]]],
    ['file' => 'hm-lavender', 'label' => 'Halfmoon Lavender', 'colors' => [[140, 100, 180], [220, 200, 240]]],

    // Plakat
    ['file' => 'pk-blacksamurai', 'label' => 'Plakat Black Samurai', 'colors' => [[20, 20, 30], [160, 170, 180]]],
    ['file' => 'pk-hellboy', 'label' => 'Plakat Hellboy', 'colors' => [[140, 10, 10], [30, 10, 10]]],
    ['file' => 'pk-redsamurai', 'label' => 'Plakat Red Samurai', 'colors' => [[150, 20, 20], [200, 200, 210]]],
    ['file' => 'pk-bluerim', 'label' => 'Plakat Blue Rim', 'colors' => [[230, 235, 240], [30, 80, 200]]],
    ['file' => 'pk-superblack', 'label' => 'Plakat Super Black', 'colors' => [[10, 10, 15], [30, 30, 40]]],

    // Koi & Nemo
    ['file' => 'koi-multicolor', 'label' => 'Koi Galaxy 4 Colors', 'colors' => [[200, 60, 30], [30, 80, 180]]],
    ['file' => 'koi-nemotiger', 'label' => 'Nemo Tiger Candy', 'colors' => [[220, 140, 30], [40, 30, 20]]],
    ['file' => 'koi-yellowfancy', 'label' => 'Yellow Fancy Copper', 'colors' => [[220, 190, 40], [180, 120, 60]]],
    ['file' => 'koi-candymulti', 'label' => 'Candy Multicolor', 'colors' => [[200, 120, 160], [120, 180, 200]]],

    // Crowntail
    ['file' => 'ct-kingcopper', 'label' => 'Crowntail King Copper', 'colors' => [[180, 120, 50], [80, 50, 20]]],
    ['file' => 'ct-blackorchid', 'label' => 'Crowntail Black Orchid', 'colors' => [[15, 10, 30], [40, 30, 120]]],
    ['file' => 'ct-royalblue', 'label' => 'Crowntail Royal Blue', 'colors' => [[20, 40, 160], [10, 20, 80]]],
    ['file' => 'ct-crossray', 'label' => 'King Crowntail Cross Ray', 'colors' => [[30, 80, 150], [180, 130, 50]]],

    // Giant
    ['file' => 'gt-nemocandy', 'label' => 'Giant Nemo Candy', 'colors' => [[220, 130, 40], [200, 60, 60]]],
    ['file' => 'gt-superred', 'label' => 'Giant Super Red', 'colors' => [[180, 10, 10], [100, 5, 5]]],
    ['file' => 'gt-avatarcopper', 'label' => 'Giant Avatar Copper', 'colors' => [[30, 30, 50], [180, 130, 60]]],

    // Double Tail
    ['file' => 'dt-rosetail', 'label' => 'Double Tail Rose', 'colors' => [[160, 20, 30], [200, 50, 60]]],
    ['file' => 'dt-fancycopper', 'label' => 'Double Tail Fancy Copper', 'colors' => [[190, 140, 70], [100, 70, 30]]],

    // Dumbo Ear
    ['file' => 'de-lavender', 'label' => 'Dumbo Ear Lavender', 'colors' => [[150, 110, 190], [230, 220, 245]]],
    ['file' => 'de-salamander', 'label' => 'Dumbo Ear Salamander', 'colors' => [[130, 50, 140], [230, 225, 235]]],

    // Alien Wild
    ['file' => 'wl-aliengreen', 'label' => 'Alien Green Wild', 'colors' => [[20, 80, 40], [40, 180, 100]]],
    ['file' => 'wl-aliencopper', 'label' => 'Alien Copper Wild', 'colors' => [[60, 40, 20], [200, 150, 80]]],

    // Special
    ['file' => 'pr-avatargordon', 'label' => 'Pair Avatar Gordon', 'colors' => [[20, 20, 40], [40, 100, 200]]],
    ['file' => 'fm-bluerim', 'label' => 'Female Blue Rim', 'colors' => [[200, 210, 230], [40, 80, 180]]],
];

// Category images
$categories = [
    ['file' => 'halfmoon', 'label' => 'Halfmoon (HM)', 'colors' => [[20, 60, 160], [60, 140, 220]]],
    ['file' => 'plakat', 'label' => 'Plakat (PK)', 'colors' => [[140, 20, 20], [40, 40, 60]]],
    ['file' => 'crowntail', 'label' => 'Crowntail (CT)', 'colors' => [[180, 120, 40], [60, 30, 10]]],
    ['file' => 'koi-nemo', 'label' => 'Koi & Nemo Galaxy', 'colors' => [[220, 100, 30], [30, 100, 180]]],
    ['file' => 'giant', 'label' => 'Giant Betta', 'colors' => [[160, 10, 10], [60, 5, 5]]],
    ['file' => 'double-tail', 'label' => 'Double Tail (DT)', 'colors' => [[170, 30, 40], [200, 140, 60]]],
    ['file' => 'dumbo-ear', 'label' => 'Dumbo Ear', 'colors' => [[140, 100, 180], [230, 220, 240]]],
    ['file' => 'alien-wild', 'label' => 'Alien & Wild', 'colors' => [[20, 80, 50], [50, 200, 120]]],
];

// Skip files that already have JPG (generated by AI)
$skipFiles = ['hm-bluerim', 'hm-superred', 'pk-avatargordon'];

function createBettaPlaceholder($outputPath, $label, $color1, $color2, $size = 800)
{
    $img = imagecreatetruecolor($size, $size);

    // Create radial gradient background
    for ($y = 0; $y < $size; $y++) {
        for ($x = 0; $x < $size; $x++) {
            // Distance from center for radial effect
            $cx = $size / 2;
            $cy = $size / 2;
            $dist = sqrt(pow($x - $cx, 2) + pow($y - $cy, 2));
            $maxDist = sqrt(pow($cx, 2) + pow($cy, 2));
            $ratio = min($dist / $maxDist, 1.0);

            // Blend inner color to outer dark
            $r = (int) ($color1[0] * (1 - $ratio) + $color2[0] * $ratio * 0.3);
            $g = (int) ($color1[1] * (1 - $ratio) + $color2[1] * $ratio * 0.3);
            $b = (int) ($color1[2] * (1 - $ratio) + $color2[2] * $ratio * 0.3);

            $col = imagecolorallocate($img, max(0, min(255, $r)), max(0, min(255, $g)), max(0, min(255, $b)));
            imagesetpixel($img, $x, $y, $col);
        }
    }

    // Add some bokeh-style light circles for depth
    for ($i = 0; $i < 15; $i++) {
        $bx = rand(50, $size - 50);
        $by = rand(50, $size - 50);
        $br = rand(5, 30);
        $alpha = rand(90, 115);
        $bokehColor = imagecolorallocatealpha($img, 255, 255, 255, $alpha);
        imagefilledellipse($img, $bx, $by, $br, $br, $bokehColor);
    }

    // Add fish silhouette shape in center
    drawFishSilhouette($img, $size, $color1, $color2);

    // Add subtle text label at bottom
    $textColor = imagecolorallocatealpha($img, 255, 255, 255, 40);
    $fontSize = 4;
    $textWidth = imagefontwidth($fontSize) * strlen($label);
    $textX = ($size - $textWidth) / 2;
    imagestring($img, $fontSize, (int) $textX, $size - 35, $label, $textColor);

    // Add "PAMULANG FISH" watermark
    $wmColor = imagecolorallocatealpha($img, 255, 255, 255, 100);
    $wmText = 'PAMULANG FISH STORE';
    $wmWidth = imagefontwidth(2) * strlen($wmText);
    imagestring($img, 2, (int) (($size - $wmWidth) / 2), $size - 20, $wmText, $wmColor);

    imagejpeg($img, $outputPath, 92);
    imagedestroy($img);
}

function drawFishSilhouette($img, $size, $color1, $color2)
{
    $cx = $size / 2;
    $cy = $size / 2;

    // Fish body (ellipse)
    $bodyW = (int) ($size * 0.45);
    $bodyH = (int) ($size * 0.22);

    // Main body gradient
    for ($i = $bodyW; $i > 0; $i--) {
        $ratio = $i / $bodyW;
        $r = (int) ($color1[0] * $ratio + $color2[0] * (1 - $ratio));
        $g = (int) ($color1[1] * $ratio + $color2[1] * (1 - $ratio));
        $b = (int) ($color1[2] * $ratio + $color2[2] * (1 - $ratio));
        // Add shimmer effect
        $shimmer = (int) (sin($i * 0.3) * 15);
        $r = max(0, min(255, $r + $shimmer));
        $g = max(0, min(255, $g + $shimmer));
        $b = max(0, min(255, $b + $shimmer));

        $bodyColor = imagecolorallocatealpha($img, $r, $g, $b, 20);
        imagefilledellipse($img, (int) $cx, (int) $cy, $i * 2, (int) ($bodyH * ($i / $bodyW) * 2), $bodyColor);
    }

    // Tail fin (triangle-ish)
    $tailColor = imagecolorallocatealpha($img, $color2[0], $color2[1], $color2[2], 30);
    $tailPoints = [
        (int) ($cx - $bodyW + 20), (int) $cy,
        (int) ($cx - $bodyW - $size * 0.15), (int) ($cy - $size * 0.18),
        (int) ($cx - $bodyW - $size * 0.15), (int) ($cy + $size * 0.18),
    ];
    imagefilledpolygon($img, $tailPoints, 3, $tailColor);

    // Tail gradient layers
    for ($i = 0; $i < 5; $i++) {
        $alpha = 40 + $i * 15;
        $layerColor = imagecolorallocatealpha($img, $color1[0], $color1[1], $color1[2], $alpha);
        $offset = $i * 8;
        $layerPoints = [
            (int) ($cx - $bodyW + 20 + $offset), (int) $cy,
            (int) ($cx - $bodyW - $size * 0.12 - $offset), (int) ($cy - $size * 0.15 + $offset),
            (int) ($cx - $bodyW - $size * 0.12 - $offset), (int) ($cy + $size * 0.15 - $offset),
        ];
        imagefilledpolygon($img, $layerPoints, 3, $layerColor);
    }

    // Dorsal fin (top)
    $dorsalColor = imagecolorallocatealpha($img, $color1[0], $color1[1], $color1[2], 35);
    $dorsalPoints = [
        (int) ($cx - $bodyW * 0.3), (int) ($cy - $bodyH),
        (int) ($cx + $bodyW * 0.2), (int) ($cy - $bodyH),
        (int) ($cx - $bodyW * 0.1), (int) ($cy - $bodyH - $size * 0.12),
    ];
    imagefilledpolygon($img, $dorsalPoints, 3, $dorsalColor);

    // Ventral fins (bottom)
    $ventralColor = imagecolorallocatealpha($img, $color2[0], $color2[1], $color2[2], 35);
    $ventralPoints = [
        (int) ($cx - $bodyW * 0.1), (int) ($cy + $bodyH),
        (int) ($cx + $bodyW * 0.3), (int) ($cy + $bodyH),
        (int) ($cx + $bodyW * 0.1), (int) ($cy + $bodyH + $size * 0.1),
    ];
    imagefilledpolygon($img, $ventralPoints, 3, $ventralColor);

    // Eye
    $eyeColor = imagecolorallocate($img, 20, 20, 20);
    $eyeHighlight = imagecolorallocate($img, 255, 255, 255);
    imagefilledellipse($img, (int) ($cx + $bodyW * 0.55), (int) ($cy - $bodyH * 0.3), 14, 14, $eyeColor);
    imagefilledellipse($img, (int) ($cx + $bodyW * 0.55 + 2), (int) ($cy - $bodyH * 0.3 - 2), 5, 5, $eyeHighlight);

    // Scale shimmer effect
    for ($i = 0; $i < 40; $i++) {
        $sx = $cx + rand(-$bodyW + 30, $bodyW - 30);
        $sy = $cy + rand(-$bodyH + 10, $bodyH - 10);
        $dist = sqrt(pow($sx - $cx, 2) / pow($bodyW, 2) + pow($sy - $cy, 2) / pow($bodyH, 2));
        if ($dist < 0.9) {
            $scaleColor = imagecolorallocatealpha($img, 255, 255, 255, rand(100, 120));
            imagefilledellipse($img, (int) $sx, (int) $sy, rand(3, 8), rand(2, 5), $scaleColor);
        }
    }
}

// Generate betta product images
$outputDir = __DIR__.'/public/images/bettas/';
$generated = 0;
$skipped = 0;

foreach ($bettas as $betta) {
    if (in_array($betta['file'], $skipFiles)) {
        echo "SKIP (has AI photo): {$betta['file']}.jpg\n";
        $skipped++;

        continue;
    }

    $outputPath = $outputDir.$betta['file'].'.jpg';
    createBettaPlaceholder($outputPath, $betta['label'], $betta['colors'][0], $betta['colors'][1]);
    echo "Generated: {$betta['file']}.jpg\n";
    $generated++;
}

// Generate category images
$catDir = __DIR__.'/public/images/categories/';
foreach ($categories as $cat) {
    $outputPath = $catDir.$cat['file'].'.jpg';
    createBettaPlaceholder($outputPath, $cat['label'], $cat['colors'][0], $cat['colors'][1], 600);
    echo "Generated category: {$cat['file']}.jpg\n";
    $generated++;
}

// Generate hero banner
$heroPath = __DIR__.'/public/images/hero-betta.jpg';
$heroImg = imagecreatetruecolor(1200, 600);

// Deep ocean gradient
for ($y = 0; $y < 600; $y++) {
    for ($x = 0; $x < 1200; $x++) {
        $ratio = $y / 600;
        $r = (int) (5 + 15 * $ratio);
        $g = (int) (20 + 40 * $ratio);
        $b = (int) (60 + 80 * $ratio);
        // Add subtle wave pattern
        $wave = sin($x * 0.02 + $y * 0.01) * 10;
        $r = max(0, min(255, $r + (int) $wave));
        $g = max(0, min(255, $g + (int) $wave));
        $b = max(0, min(255, $b + (int) $wave));
        $col = imagecolorallocate($heroImg, $r, $g, $b);
        imagesetpixel($heroImg, $x, $y, $col);
    }
}

// Add bubbles
for ($i = 0; $i < 30; $i++) {
    $bx = rand(0, 1200);
    $by = rand(0, 600);
    $br = rand(3, 20);
    $alpha = rand(80, 115);
    $bubbleColor = imagecolorallocatealpha($heroImg, 150, 200, 255, $alpha);
    imagefilledellipse($heroImg, $bx, $by, $br, $br, $bubbleColor);
    $highlight = imagecolorallocatealpha($heroImg, 220, 240, 255, $alpha + 5);
    imagefilledellipse($heroImg, $bx - 2, $by - 2, (int) ($br * 0.4), (int) ($br * 0.4), $highlight);
}

// Draw a prominent fish in center
drawFishSilhouette($heroImg, 600, [30, 100, 220], [200, 50, 50]);

imagejpeg($heroImg, $heroPath, 90);
imagedestroy($heroImg);
echo "Generated: hero-betta.jpg\n";
$generated++;

echo "\n✅ Done! Generated: {$generated} images, Skipped: {$skipped} (already have AI photos)\n";
